name: example
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=1.4.0
  - aiohttp=3.8.1
  - aiosignal=1.3.1
  - async-timeout=4.0.2
  - attrs=22.2.0
  - blas=1.0
  - blinker=1.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - cachetools=5.3.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - cryptography=3.4.8
  - cycler=0.11.0
  - freetype=2.10.4
  - frozenlist=1.3.3
  - future=0.18.3
  - google-auth=2.16.1
  - google-auth-oauthlib=0.4.6
  - grpcio=1.42.0
  - gym=0.21.0
  - idna=3.4
  - imageio=2.26.0
  - intel-openmp=2023.0.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - liblapack=3.9.0
  - libpng=1.6.37
  - libprotobuf=3.20.3
  - libtiff=4.2.0
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.3
  - markdown=3.4.1
  - matplotlib-base=3.4.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - multidict=6.0.2
  - ninja=1.11.0
  - numpy=1.23.2
  - oauthlib=3.2.2
  - openssl=1.1.1t
  - pandas=1.4.3
  - pillow=9.4.0
  - pip=22.3.1
  - protobuf=3.20.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pyjwt=2.6.0
  - pyopenssl=20.0.1
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytorch=1.12.1
  - pytz=2022.7.1
  - pyu2f=0.1.5
  - pyyaml=6.0
  - requests=2.28.2
  - requests-oauthlib=1.3.1
  - rsa=4.9
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - tbb=2021.5.0
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tk=8.6.12
  - tornado=6.2
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - werkzeug=2.1.2
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.10
  - yaml=0.2.5
  - yarl=1.7.2
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.0
  - pip:
      - importlib-metadata==4.13.0
      - panda-gym==2.0.0
      - pybullet==3.2.5
      - sb3-contrib==1.7.0
      - scipy==1.10.1
      - stable-baselines3==1.7.0
